import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';
import { Personnel } from '@/types';
import { getCertificateStatus } from '@/lib/certificateUtils';

export interface CompetenceMatrixOptions {
  personnel: Personnel[];
  projectName?: string;
  companyName?: string;
  location?: string;
}

const STATUS_SYMBOLS: Record<string, string> = {
  valid: '\u2714',    // ✔
  expiring: '\u26A0', // ⚠
  expired: '\u2716',  // ✖
};
const NOT_HELD_SYMBOL = '\u2014'; // —

export function generateCompetenceMatrixPdf(options: CompetenceMatrixOptions): jsPDF {
  const { personnel, projectName, companyName, location } = options;
  const doc = new jsPDF('l'); // landscape
  const pageWidth = doc.internal.pageSize.getWidth();
  const generatedDate = format(new Date(), 'd MMM yyyy \u00B7 HH:mm');

  // Collect unique certificate types across all personnel, sorted alphabetically
  const certTypeSet = new Set<string>();
  personnel.forEach(p => {
    p.certificates.forEach(c => {
      certTypeSet.add(c.name);
    });
  });
  const certTypes = Array.from(certTypeSet).sort((a, b) => a.localeCompare(b));

  // Build header rendering function for use on every page via didDrawPage
  const drawHeader = (pageNumber: number, pageCount: number) => {
    doc.setPage(pageNumber);
    let y = 12;

    // Title
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 0, 0);
    doc.text('Personnel Competence Matrix', 14, y);
    y += 8;

    // Info block — two columns
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(80, 80, 80);

    const leftCol = 14;
    const rightCol = pageWidth / 2 + 20;

    // Left column
    doc.text(`Project: ${projectName || 'Personnel Overview'}`, leftCol, y);
    if (companyName) {
      doc.text(`Company: ${companyName}`, rightCol, y);
    }
    y += 4.5;

    if (location) {
      doc.text(`Location: ${location}`, leftCol, y);
    }
    doc.text(`Generated: ${generatedDate}`, rightCol, y);
    y += 4.5;
    doc.text('Generated by FlowSert', rightCol, y);

    doc.setTextColor(0, 0, 0);
  };

  // Build table data
  const tableHead = ['Personnel', 'Role', ...certTypes];
  const tableBody = personnel.map(person => {
    const row: string[] = [person.name, person.role];
    certTypes.forEach(certType => {
      const cert = person.certificates.find(c => c.name === certType);
      if (!cert) {
        row.push(NOT_HELD_SYMBOL);
      } else {
        const status = getCertificateStatus(cert.expiryDate);
        row.push(STATUS_SYMBOLS[status] || NOT_HELD_SYMBOL);
      }
    });
    return row;
  });

  // Dynamic column styles: first two left-aligned, rest centered
  const columnStyles: Record<number, any> = {
    0: { halign: 'left' as const, cellWidth: 40 },
    1: { halign: 'left' as const, cellWidth: 25 },
  };

  // Render table
  const headerHeight = 30; // space reserved for our custom header
  autoTable(doc, {
    startY: headerHeight,
    head: [tableHead],
    body: tableBody,
    theme: 'grid',
    showHead: 'everyPage',
    margin: { left: 14, right: 14, top: headerHeight },
    headStyles: {
      fillColor: [50, 50, 50],
      textColor: [255, 255, 255],
      fontSize: 7,
      fontStyle: 'bold',
      halign: 'center',
      valign: 'middle',
    },
    bodyStyles: {
      fontSize: 8,
      halign: 'center',
      valign: 'middle',
    },
    columnStyles,
    styles: {
      cellPadding: 2,
      lineWidth: 0.2,
      lineColor: [180, 180, 180],
    },
    didDrawPage: () => {
      // Header will be drawn after table is complete (we need page count)
    },
  });

  const finalY = (doc as any).lastAutoTable?.finalY || headerHeight + 20;

  // Legend — on last page, below table
  const lastPage = doc.getNumberOfPages();
  doc.setPage(lastPage);
  const pageHeight = doc.internal.pageSize.getHeight();
  let legendY = Math.min(finalY + 10, pageHeight - 25);

  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(80, 80, 80);
  doc.text(
    `${STATUS_SYMBOLS.valid} Valid    ${STATUS_SYMBOLS.expiring} Expiring within warning period    ${STATUS_SYMBOLS.expired} Expired    ${NOT_HELD_SYMBOL} Not held / not applicable`,
    14,
    legendY
  );

  // Draw headers and footers on every page
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    drawHeader(i, pageCount);

    // Footer
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `Generated on ${generatedDate} | Page ${i} of ${pageCount} | Generated by FlowSert`,
      pageWidth / 2,
      pageHeight - 8,
      { align: 'center' }
    );
  }

  doc.setTextColor(0, 0, 0);
  return doc;
}
