import jsPDF from 'jspdf';
import * as pdfjsLib from 'pdfjs-dist';
import pdfjsWorker from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
import { format } from 'date-fns';
import { Personnel, Certificate } from '@/types';
import { supabase } from '@/integrations/supabase/client';

// Ensure pdf.js worker is configured
pdfjsLib.GlobalWorkerOptions.workerSrc = pdfjsWorker;

export interface CertificateBundleOptions {
  person: Personnel;
  companyName?: string;
  projectName?: string;
  onProgress?: (current: number, total: number, label: string) => void;
}

export interface CertificateBundleResult {
  doc: jsPDF;
  included: number;
  skipped: number;
}

const MAX_CERTIFICATES = 30;
const MAX_PAGES = 200;
const A4_WIDTH = 210;
const A4_HEIGHT = 297;
const MARGIN = 14;
const CONTENT_WIDTH = A4_WIDTH - MARGIN * 2;
const CONTENT_HEIGHT = A4_HEIGHT - MARGIN * 2 - 10; // leave space for footer

/**
 * Extract the storage path from a documentUrl (handles full URLs and relative paths)
 */
function extractStoragePath(documentUrl: string): string {
  if (documentUrl.includes('certificate-documents/')) {
    const match = documentUrl.match(/certificate-documents\/(.+)/);
    if (match) return match[1];
  }
  return documentUrl;
}

/**
 * Detect file type from URL/path extension
 */
function getFileType(url: string): 'pdf' | 'image' | 'unknown' {
  const ext = url.split('.').pop()?.toLowerCase().split('?')[0] || '';
  if (ext === 'pdf') return 'pdf';
  if (['jpg', 'jpeg', 'png'].includes(ext)) return 'image';
  return 'unknown';
}

/**
 * Get image format for jsPDF from extension
 */
function getImageFormat(url: string): 'JPEG' | 'PNG' {
  const ext = url.split('.').pop()?.toLowerCase().split('?')[0] || '';
  if (ext === 'png') return 'PNG';
  return 'JPEG';
}

/**
 * Add the cover page to the PDF
 */
function addCoverPage(
  doc: jsPDF,
  person: Personnel,
  companyName?: string,
  projectName?: string,
) {
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 60;

  // Title
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text('CERTIFICATE BUNDLE', pageWidth / 2, y, { align: 'center' });
  y += 8;

  // Subtitle
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(128, 128, 128);
  doc.text('FlowSert Workforce Compliance', pageWidth / 2, y, { align: 'center' });
  y += 20;

  // Metadata block (left-aligned, muted grey)
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);

  if (companyName) {
    doc.text(`Company: ${companyName}`, MARGIN, y);
    y += 5;
  }
  if (projectName) {
    doc.text(`Project: ${projectName}`, MARGIN, y);
    y += 5;
  }
  doc.text(`Person: ${person.name}`, MARGIN, y);
  y += 5;
  doc.text(`Generated: ${format(new Date(), 'd MMM yyyy · HH:mm')}`, MARGIN, y);
  y += 8;

  // Thin divider line
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y, pageWidth - MARGIN, y);

  // Reset text color
  doc.setTextColor(0, 0, 0);
}

/**
 * Add a separator page before each certificate document
 */
function addSeparatorPage(doc: jsPDF, cert: Certificate) {
  doc.addPage();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 60;

  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text(cert.name, pageWidth / 2, y, { align: 'center' });
  y += 16;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(80, 80, 80);

  if (cert.issuingAuthority) {
    doc.text(`Issuing authority: ${cert.issuingAuthority}`, MARGIN, y);
    y += 6;
  }
  doc.text(`Issue date: ${cert.dateOfIssue ? format(new Date(cert.dateOfIssue), 'd MMM yyyy') : 'N/A'}`, MARGIN, y);
  y += 6;
  doc.text(`Expiry date: ${cert.expiryDate ? format(new Date(cert.expiryDate), 'd MMM yyyy') : 'Does not expire'}`, MARGIN, y);
  y += 12;

  // Thin divider
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y, pageWidth - MARGIN, y);

  doc.setTextColor(0, 0, 0);
}

/**
 * Add footers to every page of the document
 */
function addFooters(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(160, 160, 160);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, pageHeight - 8, { align: 'center' });
    doc.text('Generated by FlowSert', pageWidth - MARGIN, pageHeight - 8, { align: 'right' });
  }
}

/**
 * Generate a merged certificate bundle PDF for a single person.
 * Downloads all certificate documents from storage and merges them into one PDF.
 */
export async function generateCertificateBundlePdf(
  options: CertificateBundleOptions,
): Promise<CertificateBundleResult> {
  const { person, companyName, projectName, onProgress } = options;

  // Filter certificates with documents, sort alphabetically
  const certsWithDocs = person.certificates
    .filter(c => c.documentUrl)
    .sort((a, b) => a.name.localeCompare(b.name));

  if (certsWithDocs.length === 0) {
    throw new Error('No certificates with uploaded documents found for this person.');
  }

  if (certsWithDocs.length > MAX_CERTIFICATES) {
    throw new Error(
      `This person has ${certsWithDocs.length} certificates with documents, which exceeds the limit of ${MAX_CERTIFICATES}. Please contact support for large exports.`,
    );
  }

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  // Cover page
  addCoverPage(doc, person, companyName, projectName);

  let included = 0;
  let skipped = 0;

  for (let i = 0; i < certsWithDocs.length; i++) {
    const cert = certsWithDocs[i];
    onProgress?.(i + 1, certsWithDocs.length, cert.name);

    // Add separator page
    addSeparatorPage(doc, cert);

    const storagePath = extractStoragePath(cert.documentUrl!);
    const fileType = getFileType(cert.documentUrl!);

    if (fileType === 'unknown') {
      skipped++;
      continue;
    }

    // Download document from storage
    const { data: blob, error } = await supabase.storage
      .from('certificate-documents')
      .download(storagePath);

    if (error || !blob) {
      console.warn(`Failed to download certificate document: ${storagePath}`, error?.message);
      skipped++;
      continue;
    }

    try {
      if (fileType === 'pdf') {
        // Render PDF pages using pdf.js
        const arrayBuffer = await blob.arrayBuffer();
        const pdfDoc = await pdfjsLib.getDocument({ data: arrayBuffer }).promise;
        const numPages = pdfDoc.numPages;

        for (let pageNum = 1; pageNum <= numPages; pageNum++) {
          // Page count safety check
          if (doc.getNumberOfPages() > MAX_PAGES) {
            throw new Error(
              `Certificate bundle exceeded ${MAX_PAGES} pages. Export aborted to prevent excessive file size.`,
            );
          }

          const page = await pdfDoc.getPage(pageNum);
          const viewport = page.getViewport({ scale: 1.5 });

          const canvas = document.createElement('canvas');
          const context = canvas.getContext('2d');
          if (!context) continue;

          canvas.width = viewport.width;
          canvas.height = viewport.height;

          await page.render({ canvasContext: context, viewport }).promise;

          const imgData = canvas.toDataURL('image/jpeg', 0.85);

          doc.addPage();

          // Scale to fit within margins
          const ratio = Math.min(
            CONTENT_WIDTH / (viewport.width * 0.264583), // px to mm at 96dpi
            CONTENT_HEIGHT / (viewport.height * 0.264583),
          );
          const imgWidthMm = viewport.width * 0.264583 * ratio;
          const imgHeightMm = viewport.height * 0.264583 * ratio;
          const xOffset = MARGIN + (CONTENT_WIDTH - imgWidthMm) / 2;
          const yOffset = MARGIN + (CONTENT_HEIGHT - imgHeightMm) / 2;

          doc.addImage(imgData, 'JPEG', xOffset, yOffset, imgWidthMm, imgHeightMm);

          // Clean up canvas
          canvas.width = 0;
          canvas.height = 0;
        }

        included++;
      } else if (fileType === 'image') {
        // Handle image files
        const imgFormat = getImageFormat(cert.documentUrl!);
        const arrayBuffer = await blob.arrayBuffer();
        const base64 = btoa(
          new Uint8Array(arrayBuffer).reduce((data, byte) => data + String.fromCharCode(byte), ''),
        );
        const dataUri = `data:image/${imgFormat.toLowerCase()};base64,${base64}`;

        // Load image to get dimensions
        const img = await new Promise<HTMLImageElement>((resolve, reject) => {
          const image = new Image();
          image.onload = () => resolve(image);
          image.onerror = () => reject(new Error('Failed to load image'));
          image.src = dataUri;
        });

        doc.addPage();

        // Scale to fit within margins while maintaining aspect ratio
        const imgAspect = img.width / img.height;
        const pageAspect = CONTENT_WIDTH / CONTENT_HEIGHT;

        let imgWidthMm: number;
        let imgHeightMm: number;

        if (imgAspect > pageAspect) {
          imgWidthMm = CONTENT_WIDTH;
          imgHeightMm = CONTENT_WIDTH / imgAspect;
        } else {
          imgHeightMm = CONTENT_HEIGHT;
          imgWidthMm = CONTENT_HEIGHT * imgAspect;
        }

        const xOffset = MARGIN + (CONTENT_WIDTH - imgWidthMm) / 2;
        const yOffset = MARGIN + (CONTENT_HEIGHT - imgHeightMm) / 2;

        doc.addImage(dataUri, imgFormat, xOffset, yOffset, imgWidthMm, imgHeightMm);

        included++;
      }
    } catch (renderError) {
      // Re-throw page limit errors
      if (renderError instanceof Error && renderError.message.includes('exceeded')) {
        throw renderError;
      }
      console.warn(`Failed to render certificate document: ${cert.name}`, renderError);
      skipped++;
    }
  }

  // Add footers to all pages
  addFooters(doc);

  return { doc, included, skipped };
}
