project_id = "frgsnallgwkufyzabeje"

[functions.certificate-chat]
verify_jwt = false

[functions.send-invitation]
verify_jwt = false

[functions.extract-certificate-data]
verify_jwt = false

[functions.suggest-project-personnel]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.suggest-certificate-types]
verify_jwt = false

[functions.suggest-issuer-types]
verify_jwt = false

[functions.auto-close-projects]
verify_jwt = false